apiVersion: v1
kind: Service
metadata:
  name: image-model-sevice-app
  namespace: fraud
spec:
  selector:
    app: image-model-app
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer